################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/app_common.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/app_subghz_phy.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_flash.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_radio.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_uart.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/ring_buffer.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/rtcm_crc.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/subghz_phy_app.c \
/home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/usr_cmd.c 

OBJS += \
./Application/User/SubGHz_Phy/App/app_common.o \
./Application/User/SubGHz_Phy/App/app_subghz_phy.o \
./Application/User/SubGHz_Phy/App/drv_flash.o \
./Application/User/SubGHz_Phy/App/drv_radio.o \
./Application/User/SubGHz_Phy/App/drv_uart.o \
./Application/User/SubGHz_Phy/App/ring_buffer.o \
./Application/User/SubGHz_Phy/App/rtcm_crc.o \
./Application/User/SubGHz_Phy/App/subghz_phy_app.o \
./Application/User/SubGHz_Phy/App/usr_cmd.o 

C_DEPS += \
./Application/User/SubGHz_Phy/App/app_common.d \
./Application/User/SubGHz_Phy/App/app_subghz_phy.d \
./Application/User/SubGHz_Phy/App/drv_flash.d \
./Application/User/SubGHz_Phy/App/drv_radio.d \
./Application/User/SubGHz_Phy/App/drv_uart.d \
./Application/User/SubGHz_Phy/App/ring_buffer.d \
./Application/User/SubGHz_Phy/App/rtcm_crc.d \
./Application/User/SubGHz_Phy/App/subghz_phy_app.d \
./Application/User/SubGHz_Phy/App/usr_cmd.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/SubGHz_Phy/App/app_common.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/app_common.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/app_subghz_phy.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/app_subghz_phy.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/drv_flash.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_flash.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/drv_radio.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_radio.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/drv_uart.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/drv_uart.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/ring_buffer.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/ring_buffer.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/rtcm_crc.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/rtcm_crc.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/subghz_phy_app.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/subghz_phy_app.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Application/User/SubGHz_Phy/App/usr_cmd.o: /home/paul/Documents/RTCM_TRX_FSS_RTK/SubGHz_Phy/App/usr_cmd.c Application/User/SubGHz_Phy/App/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DCORE_CM4 -DUSE_HAL_DRIVER -DSTM32WLE5xx -c -I../../Core/Inc -I"/home/paul/Documents/RTCM_TRX_FSS_RTK/STM32CubeIDE/Drivers/STM32WLxx_Nucleo" -I../../SubGHz_Phy/App/include -I../../SubGHz_Phy/Target/include -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../Drivers/STM32WLxx_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/timer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3 -I../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../Middlewares/Third_Party/SubGHz_Phy -I../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Application-2f-User-2f-SubGHz_Phy-2f-App

clean-Application-2f-User-2f-SubGHz_Phy-2f-App:
	-$(RM) ./Application/User/SubGHz_Phy/App/app_common.cyclo ./Application/User/SubGHz_Phy/App/app_common.d ./Application/User/SubGHz_Phy/App/app_common.o ./Application/User/SubGHz_Phy/App/app_common.su ./Application/User/SubGHz_Phy/App/app_subghz_phy.cyclo ./Application/User/SubGHz_Phy/App/app_subghz_phy.d ./Application/User/SubGHz_Phy/App/app_subghz_phy.o ./Application/User/SubGHz_Phy/App/app_subghz_phy.su ./Application/User/SubGHz_Phy/App/drv_flash.cyclo ./Application/User/SubGHz_Phy/App/drv_flash.d ./Application/User/SubGHz_Phy/App/drv_flash.o ./Application/User/SubGHz_Phy/App/drv_flash.su ./Application/User/SubGHz_Phy/App/drv_radio.cyclo ./Application/User/SubGHz_Phy/App/drv_radio.d ./Application/User/SubGHz_Phy/App/drv_radio.o ./Application/User/SubGHz_Phy/App/drv_radio.su ./Application/User/SubGHz_Phy/App/drv_uart.cyclo ./Application/User/SubGHz_Phy/App/drv_uart.d ./Application/User/SubGHz_Phy/App/drv_uart.o ./Application/User/SubGHz_Phy/App/drv_uart.su ./Application/User/SubGHz_Phy/App/ring_buffer.cyclo ./Application/User/SubGHz_Phy/App/ring_buffer.d ./Application/User/SubGHz_Phy/App/ring_buffer.o ./Application/User/SubGHz_Phy/App/ring_buffer.su ./Application/User/SubGHz_Phy/App/rtcm_crc.cyclo ./Application/User/SubGHz_Phy/App/rtcm_crc.d ./Application/User/SubGHz_Phy/App/rtcm_crc.o ./Application/User/SubGHz_Phy/App/rtcm_crc.su ./Application/User/SubGHz_Phy/App/subghz_phy_app.cyclo ./Application/User/SubGHz_Phy/App/subghz_phy_app.d ./Application/User/SubGHz_Phy/App/subghz_phy_app.o ./Application/User/SubGHz_Phy/App/subghz_phy_app.su ./Application/User/SubGHz_Phy/App/usr_cmd.cyclo ./Application/User/SubGHz_Phy/App/usr_cmd.d ./Application/User/SubGHz_Phy/App/usr_cmd.o ./Application/User/SubGHz_Phy/App/usr_cmd.su

.PHONY: clean-Application-2f-User-2f-SubGHz_Phy-2f-App

